Rtc 398 file endpoint
jellyfish-dev/jellyfish pull request #123
Opened 2023-11-30 15:34 UTC by roznawsk

## Acknowledging the stipulations set forth:
 - [ ] I hereby confirm that a Pull Request involving updates to the Software Development Kit (SDK) has been smoothly merged, currently awaits processing, or is otherwise deemed unnecessary in this context.
 - [ ] I also affirm that another Pull Request, specifically addressing updates to the documentation body (commonly referred to as 'docs'), has either been successfully incorporated, is in the process of review, or is considered superfluous under the prevailing circumstances.

2023-12-01 11:57 UTC, sgfn approved these changes

2023-12-01 11:57 UTC, sgfn commented on lib/jellyfish_web/api_spec/component/file.ex
> +          description: "Path to track file. Must be either OPUS or h264",
Correct me if I'm wrong, but I think this should be specified

```suggestion
          description: "Path to track file. Must be either OPUS encapsulated in OGG or raw h264",
```

2023-12-01 11:57 UTC, sgfn commented on test/jellyfish_web/controllers/component_controller_test.exs
> +
Why this change?

2023-12-01 13:47 UTC, Karolk99 approved these changes
"Don’t you think that passing only the filename rather than the entire filepath would be a better idea? After all, someone would need to have access to the server where Jellyfish is deployed.

What are your thoughts on passing only the filename or a filepath that could be appended to a `root_path`? This `root_path` could be configurable via the settings. 
This approach might also allow us to add a feature where these files could be sent to Jellyfish via API."

2023-12-01 13:47 UTC, Karolk99 commented on lib/jellyfish/component/file.ex
> +      track_config = get_track_config(file_path)
```suggestion
         :ok <- validate_file_path(valid_opts.filePath),
         {:ok, track_config} <- get_track_config(valid_opts.filePath) do
```

2023-12-01 13:47 UTC, Karolk99 commented on lib/jellyfish/component/file.ex
> +  end
```suggestion
  defp validate_file_path(file_path) do
    if File.exists?(file_path), do: :ok, else: {:error, :file_does_not_exist}
  end
```

2023-12-01 13:47 UTC, Karolk99 commented on lib/jellyfish/component/file.ex
> +  end
```suggestion
  defp do_get_track_config(".opus") do
    %FileEndpoint.TrackConfig{
      type: :audio,
      encoding: :OPUS,
      clock_rate: 48_000,
      fmtp: %FMTP{pt: 108}
    }
  end
  
  defp do_get_track_config(_wrong_extension), do {:error, :invalid_extension}
```

2023-12-01 13:55 UTC, Karolk99 requested changes
security breach

2023-12-04 09:05 UTC, mickel8 commented on lib/jellyfish/component/file.ex
> +  defp do_get_track_config(_extension), do: {:error, :invalid_extension}
I would favor `invalid_file_extension` or `unsupported_file_type`.

2023-12-04 14:37 UTC, roznawsk commented on config/runtime.exs
> +    System.get_env("JF_MEDIA_FILES_PATH", "jellyfish_media_files") |> Path.expand(),
I think we should be using a single path, `JF_RESOURCE_BASE_PATH` sounds good.

2023-12-04 14:46 UTC, roznawsk commented on lib/jellyfish/room.ex
> +  def handle_info(%EndpointMessage{endpoint_id: endpoint_id, message: :tracks_added}, state) do
That's a good idea.

2023-12-05 11:10 UTC, Karolk99 requested changes

2023-12-05 13:28 UTC, roznawsk commented on lib/jellyfish/room.ex
> -    Engine.terminate(engine_pid, asynchronous?: true, timeout: 10_000)
The API of engine changed - the `terminate` function takes no options.

2023-12-05 16:13 UTC, Karolk99 commented on lib/jellyfish/room.ex
> -    Engine.terminate(engine_pid, asynchronous?: true, timeout: 10_000)
merged

2023-12-06 10:18 UTC, Karolk99 approved these changes

2023-12-06 14:02 UTC, Karolk99 commented on test/jellyfish_web/controllers/component_controller_test.exs
> +
I suggest adding one more test for the file path that leads outside of base_path

2023-12-06 14:18 UTC, Karolk99 commented on lib/jellyfish/component/file.ex
> +  end
There is one edge case that is not handled properly: "." in this case, this function will return true even though it's not "inside" the directory.
I implemented a similar function in this PR: https://github.com/jellyfish-dev/jellyfish/pull/127

2023-12-06 16:53 UTC, mickel8 approved these changes

2023-12-08 12:10 UTC, Karolk99 approved these changes

2023-12-08 12:19 UTC, merged