[RTC-192] RTSP component
jellyfish-dev/jellyfish pull request #28
Opened 2023-04-12 17:03 UTC by sgfn

WIP:
- more higher-level tests TBA
- schema variables will be converted to camelCase
- README for the example TBA
- possibly other things

2023-04-12 17:09 UTC, sgfn commented on lib/jellyfish/component/rtsp.ex
> +    with {:ok, valid_opts} <- OpenApiSpex.cast_value(options, ApiSpec.Component.RTSP.schema()) do
[The docs](https://hexdocs.pm/open_api_spex/3.16.1/readme.html#validating-and-casting-params) describe a way to enable global validation of requests, which can be done by plugging `OpenApiSpex.Plug.CastAndValidate` in the component controller.

I tried to use that option but couldn't get it to work. Will look more into it.

2023-04-12 17:12 UTC, sgfn commented on lib/jellyfish_web/api_spec/component.ex
> +      },
Right now, the discriminator isn't used -- we might consider dropping it altogether

2023-04-17 12:35 UTC, mickel8 requested changes

2023-04-17 12:35 UTC, mickel8 commented on lib/jellyfish/component/rtsp.ex
> +          {Atom.to_string(k) |> Macro.underscore() |> String.to_atom(), v}
I am not sure if we can safely use Macro.underscore here :thinking: 

```
This function was designed to format language identifiers/tokens with the underscore-slash format, that's why it belongs to the [Macro](https://hexdocs.pm/elixir/Macro.html#content) module. Do not use it as a general mechanism for underscoring strings as it does not support Unicode or characters that are not valid in Elixir identifiers.
```

2023-04-17 12:35 UTC, mickel8 commented on mix.exs
> +      {:membrane_rtc_engine, github: "jellyfish-dev/membrane_rtc_engine", branch: "master"},
master is default branch

2023-04-17 12:35 UTC, mickel8 commented on test/jellyfish/component/rtsp_test.exs
> +  test "error on no sourceUri" do
```suggestion
  test "missing required sourceUri" do
```

2023-04-17 12:35 UTC, mickel8 commented on test/jellyfish_web/controllers/component_controller_test.exs
Could we create two, separate `describe` blocks? One for hls tests and another for rtsp tests? Also, let's remove `@component_type` attribute from l:6

2023-04-17 14:21 UTC, sgfn commented on lib/jellyfish/component/rtsp.ex
> +    with {:ok, valid_opts} <- OpenApiSpex.cast_value(options, ApiSpec.Component.RTSP.schema()) do
After consideration, we've decided to stick with the current approach when it comes to validation.

2023-04-17 15:25 UTC, sgfn commented on lib/jellyfish_web/api_spec/component.ex
> +      },
Dropped the discriminator

2023-04-17 22:43 UTC, mickel8 approved these changes

2023-04-17 22:43 UTC, mickel8 commented on test/jellyfish_web/controllers/component_controller_test.exs
> +    test "renders errors when component type is invalid", %{conn: conn, room_id: room_id} do
Move this one and the one from line 46 out of describe

2023-04-19 08:48 UTC, LVala approved these changes
👍

2023-04-21 10:07 UTC, merged