Change enforceEncoding to enforcedVideoCodec
jellyfish-dev/jellyfish pull request #55
Opened 2023-07-17 11:06 UTC by Karolk99

2023-07-17 11:52 UTC, roznawsk approved these changes
🦭

2023-07-17 13:25 UTC, roznawsk requested changes

2023-07-17 13:25 UTC, roznawsk commented on lib/jellyfish/room.ex
> +  defp check_video_codec(_codec, Jellyfish.Component.HLS), do: {:error, :wrong_codec}
[nitpick] imo this sounds better in the technical context
```suggestion
  defp check_video_codec(_codec, Jellyfish.Component.HLS), do: {:error, :invalid_codec}
```

2023-07-17 13:25 UTC, roznawsk commented on test/jellyfish_web/controllers/component_controller_test.exs
> +    room_conn = post(conn, ~p"/room", enforcedVideoCodec: "h264")
I think that h264 should be enforced only in the HLS component test, so we test other codecs as well.
You can create a setup block only for the `describe "create hls component"`

2023-07-17 13:30 UTC, LVala approved these changes

2023-07-17 13:39 UTC, roznawsk approved these changes

2023-07-17 15:15 UTC, roznawsk approved these changes

2023-07-18 07:57 UTC, LVala approved these changes

2023-07-18 10:21 UTC, merged