[RTC-78] Setup CI
jellyfish-dev/jellyfish pull request #6
Opened 2023-01-26 11:40 UTC by LVala

2023-01-31 07:27 UTC, Rados13 commented on lib/jellyfish_web.ex
> +           [{:__aliases__, [...], [...]}, ...]}
I am not sure if these specs are useful in any way.

2023-01-31 07:27 UTC, Rados13 commented on test/jellyfish_test.exs
>  end
I think that currently, we could remove this file.

2023-01-31 22:08 UTC, mickel8 requested changes

2023-01-31 22:08 UTC, mickel8 commented on mix.exs
> +      docs: docs(),
It is very unlikely that we will use `ex_doc` for documentation, could we remove it?

2023-01-31 22:08 UTC, mickel8 commented on .credo.exs
> +          "lib/jellyfish_web/telemetry.ex"
If the reason of ignoring `jellyfish_web.ex` and `telemetry.ex` is the requirement for specs for public functions, I would favor disabling ` Credo.Check.Readability.Specs` instead

2023-02-01 08:12 UTC, Rados13 approved these changes

2023-02-01 09:49 UTC, LVala commented on lib/jellyfish_web/views/error_helpers.ex
>    def translate_error({msg, opts}) do
I also removed `error_view.ex`. We probably won't be using templates anyway.

2023-02-01 17:37 UTC, mickel8 approved these changes

2023-02-01 17:37 UTC, mickel8 commented on mix.exs
> +      homepage_url: "https://membrane.stream",
Sounds like it can be remove too, can't it?

2023-02-01 19:18 UTC, merged